name: Build

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: spotifyd
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: Spotifyd
          repo: spotifyd
          excludes: prerelease, draft
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/spotifyd:latest, ${{ github.repository_owner }}/spotifyd:${{ steps.spotifyd.outputs.release }}
          build-args: SPOTIFYD_VERSION=${{ steps.spotifyd.outputs.release }}
